### ISSUE TITLE
Prevent involuntary data sharing with google

### ISSUE THREAD

**Issue by MarHerUMR** [h5p/h5p-hub-client#3]
I'm trying the h5p WordPress plugin with the _Use H5P Hub_ option disabled. When entering the editor of a h5p item the editor loads the `h5p-hub-client.css`. The style includes the _Open Sans_ font from Google Fonts. The user is not notified about the usage of Google Fonts and therefore can't consent into sharing data with google.

It would be great to avoid the problem by simply serving the font files locally from your WordPress.

**Comment by fnoks** [comment]
Thank you for reporting this. We will fix this in the next WordPress release.
